app4/urls.py
from django.urls import path
from app4.views import *
app_name='app4'

urlpatterns=[path('sthird/',sthird,name='sthird'),]

project4/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('second/',second,name='second'),
     path('app4/',include('app4.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app4/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.


def first(request):
    return render(request,'first.html')

def second(request):
    return render(request,'second.html')

app4/views.py
from django.shortcuts import render

# Create your views here.
def sthird(request):
    return render(request,'sthird.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> this is first html file </h1>
    <a href="{% url 'second' %}"> go  to second</a>
    <br>
    <a href="{% url 'app4:sthird' %}">Third html</a>
    </center>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> this is second html file </h1>
    <a href="{% url 'first' %}"> go  to first</a>
    <br>
    <a href="{% url 'app4:sthird' %}">Sthird Html page</a>
    </center>
</body>
</html>

templates/sthird.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> this is app4  sthird html file </h1>
        <h2> we are using specific urls for run this render </h2>
    <a href="{% url 'first' %}"> go  to first</a>
    <br>
    <a href="{% url 'second' %}"> go  to first</a>
    </center>
</body>
</html>